/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import java.sql.*;
import java.sql.DriverManager;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
    import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.text.*;
import java.awt.print.*;
import java.util.Calendar;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Vishal kumar
 */
public class Add_emp extends javax.swing.JFrame {
    Connection con=null;
 ResultSet rs=null,rs1=null;
    PreparedStatement pstmt=null;
    int flag;


    /**
     * Creates new form Add_emp
     */
    public Add_emp() {
        initComponents();
         
         try{
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\sp_office_emp.accdb");
        }catch(Exception e){
            System.out.println("problem in connection"+e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        txtsmall_p = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtb = new javax.swing.JTextField();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnsubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txta = new com.toedter.calendar.JDateChooser();
        old_rad = new javax.swing.JRadioButton();
        new_rad = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtprize = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtplace = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtbig_p = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtm = new java.awt.TextArea();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 650, 240, 60);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("बैज नंबर ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 290, 100, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("जन्मतिथि");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(740, 290, 140, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("प्र.आर/ आरक्षक का नाम");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 290, 140, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("कुल छोटी सजा");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 400, 140, 30);

        txtn.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtn);
        txtn.setBounds(220, 330, 250, 30);

        txtsmall_p.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtsmall_p);
        txtsmall_p.setBounds(210, 440, 140, 30);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("पदस्थापना इकाई बिलासपुर");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 210, 190, 50);

        txtb.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtb);
        txtb.setBounds(50, 330, 140, 30);

        txtdob.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txtdob);
        txtdob.setBounds(740, 330, 160, 30);

        btnsubmit.setBackground(new java.awt.Color(204, 204, 204));
        btnsubmit.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(102, 51, 0));
        btnsubmit.setText("रक्षित करे");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit);
        btnsubmit.setBounds(900, 430, 130, 30);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("आरक्षक एवम् प्रधान आरक्षकों का सेवा विवरण जोड़े  ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 160, 500, 40);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("आने वाली समयमान वृधि दिनांक");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(930, 290, 180, 30);

        txta.setDateFormatString("dd-MMM-yyyy");
        jPanel1.add(txta);
        txta.setBounds(930, 330, 160, 30);

        old_rad.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        old_rad.setText("पुराना कर्मचारी");
        old_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                old_radActionPerformed(evt);
            }
        });
        jPanel1.add(old_rad);
        old_rad.setBounds(470, 230, 160, 30);

        new_rad.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        new_rad.setText("नया कर्मचारी");
        new_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_radActionPerformed(evt);
            }
        });
        jPanel1.add(new_rad);
        new_rad.setBounds(880, 230, 160, 33);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("छोटी और बड़ी सजा 5 वर्षों में (संछेप में लिखें)");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(590, 400, 250, 30);

        txtprize.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtprize);
        txtprize.setBounds(380, 440, 150, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("गृह थाना /जिला");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 290, 140, 30);

        txtplace.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtplace);
        txtplace.setBounds(500, 330, 210, 30);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("कुल बड़ी सजा");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 400, 140, 30);

        txtbig_p.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtbig_p);
        txtbig_p.setBounds(60, 440, 120, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setText("वापस");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(40, 560, 100, 30);
        jPanel1.add(txtm);
        txtm.setBounds(590, 440, 250, 110);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("कुल ईनाम");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(390, 400, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if(flag==1)
            {
            pstmt=con.prepareStatement("insert into police_emp(batch_no,emp_name,dob,joining_date,work_place,sal_incrim_date,long_pun,short_pun,reward,matter)values(?,?,?,?,?,?,?,?,?,?)");
            String b=txtb.getText();
             String n=txtn.getText();
               String j=txtplace.getText();
                String bp=txtsmall_p.getText();
               String sp=txtbig_p.getText();
               String prize=txtprize.getText();
               String reward=txtm.getText();
               pstmt.setString(1,b);
               pstmt.setString(3,((JTextField)txtdob.getDateEditor().getUiComponent()).getText());
               pstmt.setString(4,((JTextField)txta.getDateEditor().getUiComponent()).getText());
             //  pstmt.setString(6,((JTextField)txti.getDateEditor().getUiComponent()).getText());
             Date d2=txta.getDate();
                Calendar cal = Calendar.getInstance();
                cal.setTime(d2);
               cal.add(Calendar.YEAR, 0); // add 5 days 
               d2 = cal.getTime();
      SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
      String d1=outputDateFormat.format(d2);
	 //    System.out.println("Output date is = "+d1);  
            pstmt.setString(6,d1);
               pstmt.setString(2,n);
               pstmt.setString(5,j);
                pstmt.setString(7,bp);
               pstmt.setString(8,sp);
               pstmt.setString(9,prize);
               pstmt.setString(10, reward);
               int i=pstmt.executeUpdate();
               pstmt.clearParameters();
               if(i>=0)
               {
                    JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                    txtb.setText("");
                    txtsmall_p.setText("");
                    txtn.setText("");
                    
               }
               else
               {
                    JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
               }
        }
            else
            {
                 pstmt=con.prepareStatement("insert into police_emp(batch_no,emp_name,dob,joining_date,work_place,sal_incrim_date,long_pun,short_pun,reward,matter)values(?,?,?,?,?,?,?,?,?,?)");
            String b=txtb.getText();
             String n=txtn.getText();
               String j=txtplace.getText();
               String bp=txtsmall_p.getText();
               String sp=txtbig_p.getText();
               String prize=txtprize.getText();
               String matter=txtm.getText();
               pstmt.setString(1,n);
               pstmt.setString(3,((JTextField)txtdob.getDateEditor().getUiComponent()).getText());
               pstmt.setString(4,((JTextField)txta.getDateEditor().getUiComponent()).getText());
             //  pstmt.setString(6,((JTextField)txti.getDateEditor().getUiComponent()).getText());
              Date d2=txta.getDate();
                Calendar cal = Calendar.getInstance();
                cal.setTime(d2);
               cal.add(Calendar.YEAR, 0); // add 5 days 
               d2 = cal.getTime();
      SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
      String d1=outputDateFormat.format(d2);
	     System.out.println("Output date is = "+d1);  
            pstmt.setString(6,d1);
               pstmt.setString(2,n);
               pstmt.setString(5,j);
               pstmt.setString(7,bp);
               pstmt.setString(8,sp);
               pstmt.setString(9,prize);
               pstmt.setString(10,matter);
               int i=pstmt.executeUpdate();
               pstmt.clearParameters();
               if(i>=0)
               {
                    JOptionPane.showMessageDialog(null,"Data inserted successfully","Data Insertion",JOptionPane.PLAIN_MESSAGE);
                    txtb.setText("");
                    txtsmall_p.setText("");
                    txtn.setText("");
                    
               }
               else
               {
                    JOptionPane.showMessageDialog(null,"Data cannot be inserted","Insertion error",JOptionPane.ERROR_MESSAGE);
               }
            }
         }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Please check batch number","Insertion  alert",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void old_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_old_radActionPerformed
        // TODO add your handling code here:
        new_rad.setSelected(false);
        flag=1;
         txtbig_p.setText("");
        txtsmall_p.setText("");
        txtprize.setText("");
    }//GEN-LAST:event_old_radActionPerformed

    private void new_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_radActionPerformed
        // TODO add your handling code here:
         old_rad.setSelected(false);
        flag=0;
        txtbig_p.setText("0");
        txtsmall_p.setText("0");
        txtprize.setText("0");
    }//GEN-LAST:event_new_radActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        home ob=new home();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton new_rad;
    private javax.swing.JRadioButton old_rad;
    private com.toedter.calendar.JDateChooser txta;
    private javax.swing.JTextField txtb;
    private javax.swing.JTextField txtbig_p;
    private com.toedter.calendar.JDateChooser txtdob;
    private java.awt.TextArea txtm;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtplace;
    private javax.swing.JTextField txtprize;
    private javax.swing.JTextField txtsmall_p;
    // End of variables declaration//GEN-END:variables
}
