/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import java.sql.*;
import java.sql.DriverManager;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
    import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.text.*;
import java.awt.print.*;
import java.util.Calendar;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Vishal kumar
 */
public class home extends javax.swing.JFrame {
    Connection con=null;
 ResultSet rs=null,rs1=null;
    PreparedStatement pstmt=null;
    int flag;
    void for_pop_up()
    {
         try 
        {
           Statement st=con.createStatement();   
         ResultSet  rs=st.executeQuery("SELECT *FROM police_emp WHERE sal_incrim_date <= Date()");
           String bn1;
           String name1;
           while(rs.next())
           {      java.util.Date d2 = null;
              bn1=rs.getString("batch_no");
               name1=rs.getString("emp_name");
               String d=rs.getString("sal_incrim_date");
               String lp=rs.getString("long_pun");
               String sp=rs.getString("short_pun");
               String rd=rs.getString("reward");
                              String pl=rs.getString("work_place");

               try
 {
      SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
    java.util.Date tempDate1=simpledateformat.parse(d);
        SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
   String  incd=outputDateFormat.format(tempDate1);
               JOptionPane.showMessageDialog(null,"बैच नंबर   "+bn1+"\n आरक्षक का नाम  "+name1+"\n कुल बड़ी सजा  "+lp+" \t कुल छोटी सजा  "+sp+"\nकुल ईनाम   "+rd+"गृह थाना /जिला  "+pl);
  } catch (ParseException ex) 
  {
        System.out.println("Parse Exception");
  }
           }
       }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection "+e);
        }
    }
    //******************************************************************************************
void this_month()
{
      try 
        {
           Statement st=con.createStatement();   
         ResultSet  rs=st.executeQuery("SELECT *FROM police_emp WHERE YEAR(sal_incrim_date) = YEAR(NOW()) AND  MONTH(sal_incrim_date) = MONTH(NOW())");
           String bn1;
           String name1;
           DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
           while (true)
           {
               int c=tm.getRowCount();
               if(c==0)
                   break;
               else 
                   tm.removeRow(0);
           }
           while(rs.next())
           {
              bn1=rs.getString("batch_no");
               name1=rs.getString("emp_name");
               Object kk[]={bn1,name1};
               tm.addRow(kk);
           }
       }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection "+e);
        }
}
//*************************************************************************
  
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
         
         try{
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\sp_office_emp.accdb");
        }catch(Exception e){
            System.out.println("problem in connection"+e);
        }
     this_month();
     for_pop_up();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtb = new javax.swing.JTextField();
        okbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        one_rad = new javax.swing.JRadioButton();
        five_rad = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("आरक्षक एवम् प्रधान आरक्षक कार्यालय");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(550, 160, 370, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("प्रिंट");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1210, 530, 130, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 51, 0));
        jButton2.setText("आरक्षकों की सूची");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 410, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 650, 240, 60);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 51, 0));
        jButton3.setText("आरक्षक को ईनाम");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(110, 550, 170, 40);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 51, 0));
        jButton4.setText("आरक्षक हटाए");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(110, 340, 170, 40);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "बैज नंबर", "आरक्षक एवं प्रधान आरक्षकों के नाम"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(890, 320, 453, 180);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("बैच नंबर");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 350, 100, 30);

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 51, 0));
        jButton5.setText("आरक्षक को सजा");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(110, 480, 170, 40);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 51, 0));
        jButton6.setText("आरक्षक जोड़े ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(110, 270, 170, 40);

        txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbActionPerformed(evt);
            }
        });
        jPanel1.add(txtb);
        txtb.setBounds(540, 350, 110, 30);

        okbtn.setBackground(new java.awt.Color(204, 204, 204));
        okbtn.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        okbtn.setForeground(new java.awt.Color(153, 51, 0));
        okbtn.setText("ठीक");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });
        jPanel1.add(okbtn);
        okbtn.setBounds(570, 410, 80, 30);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("इस महीने की आरक्षक एवम् प्रधान आरक्षकों का समयमान वेतन बढ़ोतरी की सूची");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(920, 280, 410, 30);

        one_rad.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        one_rad.setText("1 साल ");
        one_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_radActionPerformed(evt);
            }
        });
        jPanel1.add(one_rad);
        one_rad.setBounds(410, 430, 90, 30);

        five_rad.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        five_rad.setText("10 साल ");
        five_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_radActionPerformed(evt);
            }
        });
        jPanel1.add(five_rad);
        five_rad.setBounds(410, 390, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         MessageFormat header= new MessageFormat("आरक्षक एवम् प्रधान आरक्षक की सूची विवरण ");
        MessageFormat footer=new MessageFormat ("page{0,number,integer}");
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.out.println(e);
            //System.err.format("can not print %s %n"e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       list_of_emp ob=new list_of_emp();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         pardon_emp ob=new pardon_emp();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Delete_emp ob=new Delete_emp();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         suspend_emp ob=new suspend_emp();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Add_emp ob=new Add_emp();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        // TODO add your handling code here:
         String d1;             java.util.Date d2 = null;
          try{ //int tot=0;
       pstmt=con.prepareStatement("select * from police_emp where batch_no=?");
            String num=txtb.getText();
            pstmt.setString(1, num);   
            pstmt.execute();
            ResultSet  rs1=pstmt.getResultSet();
           while(rs1.next())
           {                 String d=rs1.getString("sal_incrim_date");

                try
                {
                    SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
               d2=simpledateformat.parse(d);
                                        System.out.println("Parse Exception"+d2);

                    } catch (ParseException ex)
                {
                   System.out.println("Parse Exception"+ex);
                }
           }
          }catch(Exception e)
          {
              
          }
          
          if(flag==0){
          Calendar cal = Calendar.getInstance();
                cal.setTime(d2);
               cal.add(Calendar.YEAR, 10); // add 5 year 
               d2 = cal.getTime();
                SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
       d1=outputDateFormat.format(d2);
      try
       {
       PreparedStatement    selectps=con.prepareStatement("update police_emp set sal_incrim_date=? where batch_no=?");
           selectps.setString(1, d1);
          selectps.setString(2,txtb.getText());
selectps.execute();
            JOptionPane.showMessageDialog(null,"Sucessfully Updated 10 Year");

       }catch(Exception e)
        {
        }
          }
        if(flag==1){
          Calendar cal = Calendar.getInstance();
                cal.setTime(d2);
               cal.add(Calendar.YEAR, 1); // add 1 year 
               d2 = cal.getTime();
                SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
       d1=outputDateFormat.format(d2);
      try
       {
       PreparedStatement    selectps=con.prepareStatement("update police_emp set sal_incrim_date=? where batch_no=?");
           selectps.setString(1, d1);
          selectps.setString(2,txtb.getText());
selectps.execute();
            JOptionPane.showMessageDialog(null,"Sucessfully Updated 1 Year");

       }catch(Exception e)
        {
        }
          }

    }//GEN-LAST:event_okbtnActionPerformed

    private void one_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_radActionPerformed
        // TODO add your handling code here:
        five_rad.setSelected(false);
        flag=1;
        
    }//GEN-LAST:event_one_radActionPerformed

    private void five_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_radActionPerformed
        // TODO add your handling code here:
        one_rad.setSelected(false);
        flag=0;
    }//GEN-LAST:event_five_radActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton five_rad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton okbtn;
    private javax.swing.JRadioButton one_rad;
    private javax.swing.JTextField txtb;
    // End of variables declaration//GEN-END:variables
}
