/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import java.sql.*;
import java.sql.DriverManager;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vishal kumar
 */
public class list_of_emp extends javax.swing.JFrame {
 Connection con=null;
 ResultSet rs=null,rs1=null;
    PreparedStatement pstmt=null;

    /**
     * Creates new form list_of_emp
     */
    public list_of_emp() {
        initComponents();
        
         try{
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\sp_office_emp.accdb");
        }catch(Exception e){
            System.out.println("problem in connection"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        showall = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 650, 240, 60);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("आरक्षक एवम् प्रधान आरक्षकों का सेवा विवरण की सूची");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 160, 530, 40);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("बैज नंबर ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 230, 100, 30);

        txtn.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtn);
        txtn.setBounds(580, 270, 140, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("प्रिंट");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(970, 380, 130, 30);

        showall.setBackground(new java.awt.Color(204, 204, 204));
        showall.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        showall.setForeground(new java.awt.Color(102, 51, 0));
        showall.setText("सभी दिखाये");
        showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallActionPerformed(evt);
            }
        });
        jPanel1.add(showall);
        showall.setBounds(330, 270, 130, 30);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "बैज नंबर", "प्र.आर /आरक्षक का नाम ", "जन्मतिथि", "पिछला समयमान दिनांक", "गृह थाना / जिला", "समयमान वेतन बढ़ोतरी दिनांक"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 430, 920, 170);

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("या");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(500, 270, 50, 30);

        show.setBackground(new java.awt.Color(204, 204, 204));
        show.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(102, 51, 0));
        show.setText("दिखाये");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show);
        show.setBounds(750, 270, 130, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setText("वापस");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(170, 380, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         MessageFormat header= new MessageFormat("आरक्षक एवम् प्रधान आरक्षक की सूची विवरण ");
        MessageFormat footer=new MessageFormat ("page{0,number,integer}");
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.out.println(e);
            //System.err.format("can not print %s %n"e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        home ob=new home();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
         try{ //int tot=0;
       pstmt=con.prepareStatement("select * from police_emp where batch_no=?");
            String num=txtn.getText();
            pstmt.setString(1, num);   
            pstmt.execute();
            ResultSet  rs1=pstmt.getResultSet();
           String batch;
           String dob = null,d1,join = null,d2,dist,incd = null,d3;
           String name;
           DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }
           
                while(rs1.next())
                {
                  batch=rs1.getString("batch_no");
                  name=rs1.getString("emp_name");
                    dist=rs1.getString("work_place");
                   d3=rs1.getString("sal_incrim_date");
                   d2=rs1.getString("joining_date");
                   d1=rs1.getString("dob");
try
 {
      SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
    java.util.Date tempDate1=simpledateformat.parse(d1);
        java.util.Date tempDate2=simpledateformat.parse(d2);
    java.util.Date tempDate3=simpledateformat.parse(d3);

    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
    //System.out.println("Output date is = "+outputDateFormat.format(tempDate));
     dob=outputDateFormat.format(tempDate1);
          join=outputDateFormat.format(tempDate2);
     incd=outputDateFormat.format(tempDate3);
  } catch (ParseException ex) 
  {
        System.out.println("Parse Exception");
  }

                 Object kk[]={batch,name,dob,join,dist,incd};
                    tm.addRow(kk);
                }
          //  selectps.clearParameters();
       
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,"couldnotfound  "+e);
      }
    }//GEN-LAST:event_showActionPerformed

    private void showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallActionPerformed
        // TODO add your handling code here:
        try{ //int tot=0;
       Statement st=con.createStatement();   
     ResultSet      rs1=st.executeQuery("select * from police_emp ");
           String batch;
           String dob = null,d1,join = null,d2,dist,incd = null,d3;
           String name;
           DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }
           
                while(rs1.next())
                {
                  batch=rs1.getString("batch_no");
                  name=rs1.getString("emp_name");
                    dist=rs1.getString("work_place");
                   d3=rs1.getString("sal_incrim_date");
                   d2=rs1.getString("joining_date");
                   d1=rs1.getString("dob");
try
 {
      SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
    java.util.Date tempDate1=simpledateformat.parse(d1);
        java.util.Date tempDate2=simpledateformat.parse(d2);
    java.util.Date tempDate3=simpledateformat.parse(d3);

    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
    //System.out.println("Output date is = "+outputDateFormat.format(tempDate));
     dob=outputDateFormat.format(tempDate1);
          join=outputDateFormat.format(tempDate2);
     incd=outputDateFormat.format(tempDate3);
  } catch (ParseException ex) 
  {
        System.out.println("Parse Exception");
  }

                 Object kk[]={batch,name,dob,join,dist,incd};
                    tm.addRow(kk);
                }
          //  selectps.clearParameters();
       
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,"couldnotfound  "+e);
      }
    }//GEN-LAST:event_showallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_of_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_of_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_of_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_of_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list_of_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton show;
    private javax.swing.JButton showall;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
