/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vishal kumar
 */
public class pardon_emp extends javax.swing.JFrame {
Connection con=null;
 ResultSet rs=null,rs1=null;
    PreparedStatement pstmt=null;
    PreparedStatement pstmt1=null;
    int reward;
    

    /**
     * Creates new form pardon_emp
     */
    public pardon_emp() {
        initComponents();
        try{
            con=DriverManager.getConnection("jdbc:ucanaccess://.\\sp_office_emp.accdb");
        }catch(Exception e){
            System.out.println("problem in connection"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtb = new javax.swing.JTextField();
        btnshow = new javax.swing.JButton();
        btninc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 10, 600, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Developed By: Madhurendra & Vishal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 650, 240, 60);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("आरक्षक एवम् प्रधान आरक्षकों को इनाम ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 160, 400, 40);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("इनाम बढ़ाये");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 340, 70, 30);

        txtb.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jPanel1.add(txtb);
        txtb.setBounds(610, 270, 140, 30);

        btnshow.setBackground(new java.awt.Color(204, 204, 204));
        btnshow.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btnshow.setForeground(new java.awt.Color(102, 51, 0));
        btnshow.setText("दिखाये");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });
        jPanel1.add(btnshow);
        btnshow.setBounds(810, 270, 130, 30);

        btninc.setBackground(new java.awt.Color(204, 204, 204));
        btninc.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btninc.setForeground(new java.awt.Color(102, 51, 0));
        btninc.setText("ठीक");
        btninc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincActionPerformed(evt);
            }
        });
        jPanel1.add(btninc);
        btninc.setBounds(710, 340, 90, 30);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "बैज नंबर", "प्र.आर /आरक्षक का नाम ", "जन्मतिथि", "भर्ती दिनांक", "गृह थाना / जिला", "वतेन बढ़ोतरी दिनांक", "ईनाम"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(15);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 520, 980, 50);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("बैज नंबर ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 260, 100, 30);

        btnback.setBackground(new java.awt.Color(204, 204, 204));
        btnback.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(153, 0, 0));
        btnback.setText("वापस");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(150, 410, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        home ob=new home();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
          try{ //int tot=0;
       pstmt=con.prepareStatement("select * from police_emp where batch_no=?");
            String batch_num=txtb.getText();
            pstmt.setString(1, batch_num);    
            pstmt.execute();
            ResultSet  rs1=pstmt.getResultSet();
        String name;
           String date1 = null,d1,d3,d2,date2 = null,date3 = null;
           String place;
           
           DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }
           
                while(rs1.next())
                {
                  batch_num=rs1.getString("batch_no");
                    name=rs1.getString("emp_name");
                   d1=rs1.getString("dob");
                   d2=rs1.getString("joining_date");
                   d3=rs1.getString("sal_incrim_date");
                   place=rs1.getString("work_place");  
                   reward=rs1.getInt("reward");    
        try
 {
      SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
    java.util.Date tempDate=simpledateformat.parse(d1);
    java.util.Date tempDate1=simpledateformat.parse(d2);
        java.util.Date tempDate2=simpledateformat.parse(d3);
    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
     date1=outputDateFormat.format(tempDate);
         date2=outputDateFormat.format(tempDate1);
         date3=outputDateFormat.format(tempDate2);
  } catch (ParseException ex) 
  {
        System.out.println("Parse Exception");
  }

                 Object kk[]={batch_num,name,date1,date2,place,date3,reward};
                    tm.addRow(kk);
                }
          //  selectps.clearParameters();
       
      }catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,"couldnotfound mkp "+e);
      }
    }//GEN-LAST:event_btnshowActionPerformed

    private void btnincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincActionPerformed
        // TODO add your handling code here:
         try 
        {
           pstmt=con.prepareStatement("update police_emp set reward = reward+1 where batch_no=?");
           String  batch=txtb.getText();
          pstmt.setString(1, batch);
                    pstmt.execute();
                                JOptionPane.showMessageDialog(null,"UPDATED");
                                
                                
                                pstmt=con.prepareStatement("select * from police_emp where batch_no=?");
            String batch_num=txtb.getText();
            pstmt.setString(1, batch_num);    
            pstmt.execute();
            ResultSet  rs1=pstmt.getResultSet();
        String name;
           String date1 = null,d1,d3,d2,date2 = null,date3 = null;
           String place;
           
           DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            while (true)
            {
                int c=tm.getRowCount();
                if(c==0)
                break;
                else
                tm.removeRow(0);
            }
           
                while(rs1.next())
                {
                  batch_num=rs1.getString("batch_no");
                    name=rs1.getString("emp_name");
                   d1=rs1.getString("dob");
                   d2=rs1.getString("joining_date");
                   d3=rs1.getString("sal_incrim_date");
                   place=rs1.getString("work_place");  
                   reward=rs1.getInt("reward");    
        try
 {
      SimpleDateFormat simpledateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
    java.util.Date tempDate=simpledateformat.parse(d1);
    java.util.Date tempDate1=simpledateformat.parse(d2);
        java.util.Date tempDate2=simpledateformat.parse(d3);
    SimpleDateFormat outputDateFormat = new SimpleDateFormat("dd-MMM-yyyy");           
     date1=outputDateFormat.format(tempDate);
         date2=outputDateFormat.format(tempDate1);
         date3=outputDateFormat.format(tempDate2);
  } catch (ParseException ex) 
  {
        System.out.println("Parse Exception");
  }

                 Object kk[]={batch_num,name,date1,date2,place,date3,reward};
                    tm.addRow(kk);
                }

        }catch(Exception e)
        {
                      JOptionPane.showMessageDialog(null,"couldnotfound mkp "+e);
        }

       
    }//GEN-LAST:event_btnincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pardon_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pardon_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pardon_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pardon_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pardon_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btninc;
    private javax.swing.JButton btnshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtb;
    // End of variables declaration//GEN-END:variables
}
